2024-04-09 16:09:47,836 - regression_class_conspiracy_logistic - INFO - Running FSS
2024-04-09 16:09:48,491 - py.warnings - WARNING - /home/cara/anaconda3/envs/redditenv/lib/python3.10/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

2024-04-09 16:09:48,494 - py.warnings - WARNING - /home/cara/anaconda3/envs/redditenv/lib/python3.10/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

2024-04-09 16:09:48,498 - py.warnings - WARNING - /home/cara/anaconda3/envs/redditenv/lib/python3.10/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

2024-04-09 16:09:48,498 - py.warnings - WARNING - /home/cara/anaconda3/envs/redditenv/lib/python3.10/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

2024-04-09 16:09:48,499 - regression_class_conspiracy_logistic - INFO - Model 1
2024-04-09 16:09:48,551 - regression_class_conspiracy_logistic - INFO - Model 2
2024-04-09 16:09:48,592 - regression_class_conspiracy_logistic - INFO - Model 3
2024-04-09 16:09:48,645 - regression_class_conspiracy_logistic - INFO - Model 4
2024-04-09 16:09:48,701 - regression_class_conspiracy_logistic - INFO - Model 5
2024-04-09 16:09:48,789 - regression_class_conspiracy_logistic - INFO - Model 6
2024-04-09 16:09:49,286 - regression_class_conspiracy_logistic - INFO - Model 7
2024-04-09 16:09:49,669 - regression_class_conspiracy_logistic - INFO - Model 8
2024-04-09 16:09:50,369 - regression_class_conspiracy_logistic - INFO - Model 9
2024-04-09 16:09:50,964 - regression_class_conspiracy_logistic - INFO - Model 10
